In [1]:
import numpy as np

In [2]:
print("Hello world")

Hello world


In [ ]:
import sklearn

In [8]:
i=45

In [6]:
print(7)

7


In [9]:
i

45

***Numpy***

In [10]:
import numpy as np

To make a numpy array

In [11]:
myarr=np.array([5,6,7,"philips"])

In [12]:
myarr

array(['5', '6', '7', 'philips'], dtype='<U11')

In [13]:
type(myarr)

numpy.ndarray

In [18]:
myarr=np.array([5,6,777777],np.int8)
#u ll get a error becoz of 777777 number if u keep np.int8 so u can give int32 int 64 for big numbers 

C:\Users\vaish\AppData\Local\Temp\ipykernel_8120\2831513465.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 777777 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  myarr=np.array([5,6,777777],np.int8)


In [19]:
myarr=np.array([5,6,777777],np.int64)


In [20]:
myarr

array([     5,      6, 777777], dtype=int64)

In [21]:
myarr[1]

6

In [22]:
myarr[0,1]#u ll get a error so make it 2 d by ([[]])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [26]:
myarr=np.array([[5,6,777777]],np.int64)


In [27]:
myarr[0,1]

6

Suppose u wanna know abt myarr

In [28]:
myarr.shape#gives the rows and columns 

(1, 3)

In [29]:
myarr.dtype

dtype('int64')

In [30]:
myarr[0,1]=45#vch means change the element that is present in the 0th row and 1 at column to 45

In [31]:
myarr

array([[     5,     45, 777777]], dtype=int64)

Array Creation methods in NUMPY 

1.Conversion from other python structures

In [32]:
listarray=[[2,3,4,5],[5,6,7,8],[3,4,2,1],[3,4,5,6]]
listarray=np.array(listarray)

In [33]:
listarray

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [3, 4, 2, 1],
       [3, 4, 5, 6]])

In [34]:
listarray.dtype

dtype('int32')

In [35]:
listarray.shape

(4, 4)

In [36]:
listarray.size

16

In [37]:
np.array({34,67,89,23,23})#Here u ll get the dtype as object it is prefered not to keep object working with 
# float int is recommended 


array({89, 34, 67, 23}, dtype=object)

Intrinsic Numpy array creation objects 

In [39]:
zeros=np.zeros((2,7))

In [40]:
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [41]:
zeros.dtype

dtype('float64')

In [42]:
zeros.shape

(2, 7)

In [43]:
zeros.size

14

In [44]:
range=np.arange(15)

In [45]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
lspace=np.linspace(1,5,12)#It gives the elements that are linerly spaced 12 elements frm 1 to 5  

In [47]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [48]:
lspace=np.linspace(1,50,5)#COncept here is not slicing but it returns such that from 
# 1 to 50 it v ll give only 5 elements 

In [49]:
lspace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [50]:
emp=np.empty((4,6))#It v ll empty the place and it v ll random all the elements 

In [51]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11260280e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037317e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 3.56036603e-307, 1.37961641e-306],
       [1.37961302e-306, 1.11259940e-306, 1.60219035e-306,
        1.11261570e-306, 1.06811354e-306, 8.34448533e-308]])

In [52]:
emp_like=np.empty_like(lspace)#here u shud pass a array 

In [53]:
emp_like

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

For creating a identity matrix

In [54]:
ide=np.identity(80)#It creates a identity matrix of 80*80

In [55]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [56]:
ide.shape

(80, 80)

#Most important 2 functions 

In [65]:
arr=np.arange(99)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
#To reshape the array

In [70]:
arr=arr.reshape(3,33)

In [72]:
arr=arr.reshape(4,39)

ValueError: cannot reshape array of size 99 into shape (4,39)

In [73]:
arr=arr.reshape(3,33)

In [74]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

To make it correct form like before 

In [77]:
arr=arr.ravel()

In [78]:
arr.shape

(99,)

In [79]:
arr=arr.ravel()

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [81]:
arr.shape

(99,)

Numpy Axis

In [82]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [83]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [86]:
ar=np.array(x)

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
ar.sum(axis=0)#Sum of every column

array([12, 15, 18])

In [89]:
ar.sum(axis=1)#Sum of every row

array([ 6, 15, 24])

In [90]:
#To do the transpose of the matrix
at=ar.T
at

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [91]:
ar.flat

In [92]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [93]:
ar.ndim#Dimension of the matrix

2

In [94]:
ar.size#No of elements in array

9

In [95]:
ar.shape#rows and columns 

(3, 3)

In [96]:
ar.nbytes#Give the size that the array occupies 

36

In [98]:
one=np.array([1,2,3,456,2])
one.argmax()#Give the max elemnts index of the argument that we pass ,this is method coz it ends with ()

3

In [99]:
one.argmin()

0

In [100]:
one.argsort()#Gives the order of the indexes it shud be arranged to form the sorted array in ascending order 

array([0, 1, 4, 2, 3], dtype=int64)

In [110]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
ar.argmin()

0

In [109]:
ar.argmax()

8

In [104]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [111]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [112]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [113]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
ar.argmax(axis=0)# in axis 0 where the max element is their it vll return

array([2, 2, 2], dtype=int64)

In [115]:
ar.argmax(axis=1)# in axis 1 where all min element is their it v ll return 


array([2, 2, 2], dtype=int64)

In [116]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [117]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [120]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [121]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [122]:
ar.ravel()#seeda hog jayega

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Matrix Operations

In [126]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
ar2=np.array([[2,3,4],[5,6,7],[4,5,6]])

In [128]:
ar2

array([[2, 3, 4],
       [5, 6, 7],
       [4, 5, 6]])

In [129]:
ar+ar2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [11, 13, 15]])

In [130]:
ar-ar2

array([[-1, -1, -1],
       [-1, -1, -1],
       [ 3,  3,  3]])

In [131]:
ar*ar2

array([[ 2,  6, 12],
       [20, 30, 42],
       [28, 40, 54]])

In [132]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [134]:
ar.sum()

45

In [135]:
ar.max()

9

In [137]:
ar.min()

1

To find the elements 

In [140]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [141]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [143]:
np.count_nonzero(ar)

9

In [144]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [145]:
import sys

In [147]:
py_ar=[0,4,55,2]

In [148]:
np_ar=np.array(py_ar)

In [149]:
#To get the size of py_ar
sys.getsizeof(1)*len(py_ar)

112

In [150]:
# To get the size of np_ar
np_ar.itemsize*np_ar.size

16

In [151]:
np_ar.tolist()

[0, 4, 55, 2]